spring:
  main:
    allow-bean-definition-overriding: true
  jms:
    servicebus:
      connection-string: ${AZURE-URL-SENDER}
      idle-timeout: 20000
      pricing-tier: basic
    listener:
      connection-string: ${AZURE-URL-LISTENER}
      idle-timeout: 20000
      pricing-tier: basic
